#!/usr/bin/env node
'use strict';
// One-time setup: creates the Ed25519 key pair that signs license keys.
//   private key -> tools/keys/license-private.pem   (NEVER commit; also paste into the Worker as a secret)
//   public key  -> recorder/src/public-key.js       (shipped inside the recorder)
// Usage: node tools/keygen.js [--force]

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const root = path.resolve(__dirname, '..');
const privPath = path.join(__dirname, 'keys', 'license-private.pem');
const pubJs = path.join(root, 'recorder', 'src', 'public-key.js');

if (fs.existsSync(privPath) && !process.argv.includes('--force')) {
  console.error(`A key already exists at ${privPath}. Re-running would invalidate every key you have sold.\nPass --force only if you really mean to rotate it.`);
  process.exit(1);
}

const { publicKey, privateKey } = crypto.generateKeyPairSync('ed25519');
const pem = privateKey.export({ type: 'pkcs8', format: 'pem' });
const pkcs8b64 = privateKey.export({ type: 'pkcs8', format: 'der' }).toString('base64');
const spkiB64 = publicKey.export({ type: 'spki', format: 'der' }).toString('base64');

fs.mkdirSync(path.dirname(privPath), { recursive: true, mode: 0o700 });
fs.writeFileSync(privPath, pem, { mode: 0o600 });
fs.writeFileSync(pubJs, `'use strict';\n// Generated by tools/keygen.js — the public half of the SIREN license signing key.\nmodule.exports = { PUBLIC_KEY_SPKI_B64: '${spkiB64}' };\n`);

console.log('Private key saved to', privPath);
console.log('Public key written to', pubJs);
console.log('\nFor the license server, run:\n  npx wrangler secret put LICENSE_PRIVATE_KEY_PKCS8\nand paste this value:\n');
console.log(pkcs8b64);
