name: Idea or feedback
description: Something you'd like added, changed or removed.
title: "[Feedback] "
labels: [feedback, from-site]
body:
  - type: markdown
    attributes:
      value: "Issues are **public**. Please don't include personal information."
  - type: input
    id: page
    attributes:
      label: Page (optional)
  - type: textarea
    id: what
    attributes:
      label: Your idea or feedback
    validations:
      required: true
