import Foundation

struct InterviewTopic: Identifiable {
    let id: String
    let title: String
    let symbol: String
    /// Shown under the title: why this matters for recreating you.
    let purpose: String
    let questions: [String]
}

/// The question bank. The aim isn't a biography; it's enough of you, your
/// stories, opinions, habits and voice, that an AI can answer the way you would.
enum InterviewPrompts {
    static let topics: [InterviewTopic] = [
        InterviewTopic(id: "roots", title: "Roots", symbol: "house",
                       purpose: "Where you come from shapes how you tell every other story.", questions: [
            "Where did you grow up, and what did it smell and sound like?",
            "Describe the house you grew up in, room by room if you can.",
            "Describe your mother the way you'd describe her to a stranger.",
            "Describe your father the way you'd describe him to a stranger.",
            "What were your grandparents like? Any you never met but heard about?",
            "What's a family story that gets told at every gathering?",
            "What did your family eat on an ordinary weeknight? On holidays?",
            "What were the rules in your house growing up, spoken and unspoken?",
            "What did your family argue about?",
            "Where does your family come from, as far back as you know?",
            "What traditions did you keep from your family, and which did you drop?",
            "What's the first thing you remember?",
        ]),
        InterviewTopic(id: "childhood", title: "Childhood", symbol: "figure.and.child.holdinghands",
                       purpose: "The small specifics of being a kid are what people love hearing about.", questions: [
            "Who was your best friend as a kid, and what did you get up to?",
            "What did you want to be when you were ten?",
            "What trouble did you get into?",
            "What were you afraid of as a child?",
            "What toys, games, shows or books did you love?",
            "What was school like for you? Favorite and worst teacher?",
            "Describe a perfect summer day when you were a kid.",
            "When did you first feel like a grown-up?",
            "What was your first job, and what did you spend the money on?",
            "What were you like as a teenager? What would your friends then have said about you?",
            "What music were you obsessed with at sixteen?",
        ]),
        InterviewTopic(id: "love", title: "Love & partners", symbol: "heart",
                       purpose: "How you love is something your family will want to hear in your words.", questions: [
            "Tell me about your first crush or first love.",
            "How did you meet your partner(s)? Tell it like a story.",
            "What made you fall for them?",
            "What was your wedding or commitment like? What went wrong that day?",
            "What's the hardest thing you and your partner got through?",
            "What do you two fight about, and how do you make up?",
            "What did you learn about love that you wish you'd known earlier?",
            "What does it look like when you love someone? How do you show it?",
            "If there's someone you lost or let go, what do you want to say about them?",
        ]),
        InterviewTopic(id: "family", title: "Children & family", symbol: "person.3",
                       purpose: "Your kids, siblings and family will be the ones talking to your AI most.", questions: [
            "What was it like to become a parent (or to decide not to)?",
            "Describe each of your children as a baby, as a kid, and now.",
            "What's a moment with each of your kids you'll never forget?",
            "What are you most proud of about each person in your family?",
            "What do you worry about for each of them?",
            "What did you get wrong as a parent, and what did you get right?",
            "What was it like growing up with your siblings? What are they like now?",
            "What do you hope your family keeps doing together after you're gone?",
            "What family recipes, sayings or traditions should never be lost?",
            "How do you want family disagreements handled after you're gone?",
        ]),
        InterviewTopic(id: "friends", title: "Friends", symbol: "person.2.wave.2",
                       purpose: "Friendships show sides of you your family may not see.", questions: [
            "Who are your closest friends, and how did each friendship start?",
            "What's the best night out you've ever had?",
            "Tell me about a friend you lost touch with or lost.",
            "What does a good friend do that most people don't?",
            "What's an adventure or trip you took with friends?",
            "Who would you call at 3am, and why them?",
        ]),
        InterviewTopic(id: "work", title: "Work & money", symbol: "briefcase",
                       purpose: "What you did all day, and what you thought about it.", questions: [
            "Walk me through every job you've had, briefly.",
            "What work are you proudest of?",
            "What was your worst boss or worst job like?",
            "What did a normal workday look like for you?",
            "What did you learn about money, and how did you learn it?",
            "Were you ever broke? Ever unexpectedly comfortable? What was that like?",
            "What would you have done for work if anything were possible?",
            "What advice would you give someone choosing a career?",
            "How did you feel about retirement (or how do you imagine it)?",
        ]),
        InterviewTopic(id: "turning", title: "Turning points", symbol: "arrow.triangle.branch",
                       purpose: "The decisions and accidents that made your life go one way and not another.", questions: [
            "What decision changed the direction of your life the most?",
            "Tell me about a time you failed and what came after.",
            "When did you feel most proud of yourself?",
            "What's something you were wrong about for a long time?",
            "Describe a moment of pure luck in your life.",
            "What's a risk you took that paid off? One that didn't?",
            "Where were you during big world events, and how did they touch your life?",
            "What's a place you moved to or left, and why?",
        ]),
        InterviewTopic(id: "hard", title: "Hard times", symbol: "cloud.rain",
                       purpose: "Your family may face the same things. What got you through matters.", questions: [
            "Describe the hardest year you've lived through.",
            "Who have you lost, and how did you grieve them?",
            "What got you through your darkest time?",
            "Have you been seriously ill or injured? What was that like?",
            "Is there a regret you still carry?",
            "Who do you owe an apology to? Who owes you one?",
            "Is there someone you forgave, or couldn't forgive?",
            "What would you say to someone in your family who's struggling the way you once did?",
        ]),
        InterviewTopic(id: "beliefs", title: "Beliefs & values", symbol: "sparkles",
                       purpose: "So your AI disagrees and agrees with people the way you would.", questions: [
            "What do you believe happens after we die?",
            "What's your relationship with religion or spirituality?",
            "What makes a life well lived?",
            "What would you fight for?",
            "What's a rule you live by that you made up yourself?",
            "What do you think is wrong with the world, and what's right with it?",
            "What do you think about politics, if you're willing to say? What do you not want your AI to talk about?",
            "What do people do that you can't stand?",
            "What do you admire most in a person?",
            "What scares you, honestly?",
            "How do you feel about dying?",
        ]),
        InterviewTopic(id: "opinions", title: "Tastes & opinions", symbol: "star",
                       purpose: "Strong little opinions make an AI feel like you instead of a greeting card.", questions: [
            "What are your favorite foods, and what will you never eat?",
            "What's the best meal you've ever had, and where?",
            "Which music, artists or songs mean the most to you, and why?",
            "What movies or shows could you watch forever?",
            "What books changed you?",
            "Which sports teams do you follow, and how seriously?",
            "What's your take on coffee vs. tea, cats vs. dogs, beach vs. mountains? Argue it.",
            "What's an unpopular opinion you hold?",
            "What's overrated? What's underrated?",
            "What do you collect, or what can't you throw away?",
            "Where's your favorite place in the world?",
        ]),
        InterviewTopic(id: "everyday", title: "Everyday you", symbol: "sun.max",
                       purpose: "Habits and routines are what people miss most, and what an AI gets wrong most.", questions: [
            "Describe a perfect ordinary day, from waking up to falling asleep.",
            "What's your morning routine? How do you take your coffee?",
            "What do you do when you can't sleep?",
            "What are your quirks, habits, and little rituals?",
            "What do you do to relax? To cheer yourself up?",
            "What's in your kitchen right now that says something about you?",
            "How do you drive? Be honest.",
            "What are you like when you're sick, hungry or tired?",
            "What do you always lose, always forget, always carry?",
            "What hobbies have you had over the years?",
        ]),
        InterviewTopic(id: "voice", title: "How you talk", symbol: "quote.bubble",
                       purpose: "The most important topic for sounding like you. Write exactly how you'd say it.", questions: [
            "What are your catchphrases and sayings? Write them exactly.",
            "What do you call the people you love? Nicknames, pet names?",
            "How do you greet people? How do you say goodbye or sign off?",
            "How do you comfort someone who's crying? Write what you'd actually say.",
            "How do you tell someone you're proud of them?",
            "What do you say when someone tells you good news?",
            "How do you act when you're annoyed? What do you say?",
            "How do you argue? Do you go quiet, get loud, make jokes?",
            "What makes you laugh, and what kind of jokes do you make?",
            "Do you swear? Which words, and when?",
            "How do you text? Emoji, capitals, punctuation, voice notes?",
            "What words or phrases do you never use?",
            "Is there an accent, dialect or second language that comes out of you?",
            "How do you give advice: gently, bluntly, with a story?",
        ]),
        InterviewTopic(id: "advice", title: "Advice", symbol: "lightbulb",
                       purpose: "What your people will come back to ask you, again and again.", questions: [
            "What advice would you give someone on the worst day of their life?",
            "What should someone know before getting married or moving in together?",
            "What should someone know about raising kids?",
            "What would you tell your younger self at 18? At 30?",
            "How should someone handle a bad boss, a breakup, a betrayal?",
            "What should a person never do?",
            "How do you make a hard decision?",
            "What do you want your loved ones to do when they miss you?",
            "What should people know about getting old?",
        ]),
        InterviewTopic(id: "messages", title: "Messages to keep", symbol: "envelope.open",
                       purpose: "Things to be said at the right moments: weddings, births, hard days. Limit each to the right person.", questions: [
            "What do you want to say to each person you love, in your own words?",
            "What would you say at your child's or grandchild's wedding?",
            "What would you say when a new baby joins the family?",
            "What would you say to someone graduating or starting a new job?",
            "What would you say to someone on the anniversary of your death?",
            "What should your AI tell someone who asks whether you were happy?",
            "What do you want people to know about how you died, if they ask?",
            "Is there anything you never said out loud that you want said now?",
        ]),
        InterviewTopic(id: "hypotheticals", title: "Would you rather", symbol: "dice",
                       purpose: "How you reason about new situations, so the AI can handle questions you never answered.", questions: [
            "If you won the lottery tomorrow, what would you do first?",
            "If you could live anywhere for a year, where and why?",
            "If you could have dinner with anyone, living or dead, who?",
            "What would you save from a fire?",
            "If one of your kids wanted to drop out to chase a dream, what would you say?",
            "If you could redo one day of your life, which and why?",
            "What would you do with one more ordinary day?",
        ]),
        InterviewTopic(id: "legacy", title: "Your legacy", symbol: "leaf",
                       purpose: "How you want to be remembered, and how your AI should behave.", questions: [
            "How do you want to be remembered?",
            "What do you hope people say at your funeral? What would you hate them to say?",
            "What do you want done with your things, and with your body?",
            "What songs should be played when people remember you?",
            "How should your AI behave? What should it never do?",
            "When should people stop talking to your AI and live their lives? What would you tell them?",
        ]),
    ]

    static var allQuestions: [String] { topics.flatMap(\.questions) }

    /// Messages someone might send you. Answering them shows exactly how you'd reply.
    static let replyScenarios: [String] = [
        "I got the job!!",
        "I'm pregnant.",
        "We broke up.",
        "Can't sleep. You up?",
        "Happy birthday!!! 🎂",
        "I failed my exam.",
        "I'm scared about the surgery tomorrow.",
        "Guess who I ran into today",
        "I think I messed up really badly.",
        "What should I make for dinner?",
        "I miss you.",
        "Are you mad at me?",
        "Mom/Dad is driving me crazy",
        "Can I borrow some money?",
        "I'm getting married!",
        "Grandma died this morning.",
        "Do you think I'm making a mistake?",
        "Look at this picture of the dog 😂",
        "I'm thinking of moving across the country.",
        "Merry Christmas! / Happy holidays!",
        "I don't know what to do with my life.",
        "Thank you for everything.",
        "I'm so proud of you.",
        "What was I like as a baby?",
        "Tell me a story.",
        "Why did you do that?",
        "I love you.",
        "Good night",
    ]
}
