// Dispatch snapshot: 911 CAD calls, multi-system emergency alerts, and
// police-call "blather" (the nature-of-call chatter from open CAD feeds).
//
// Same publishing pattern as monitor/ and scanner/: the workflow writes JSON to
// the dispatch-data branch; site/static/dispatch.html reads it from
// raw.githubusercontent.com. Nothing here writes to main or touches the index.
//
// Privacy: street addresses never leave the city adapters. CAD pins use
// round2 (~1 km); alert systems use round3 (~100 m). Sensitive call types are dropped.
//
// Usage: node dispatch/collect.mjs <outdir>

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fetchJson } from '../collector/fetch.mjs';
import { CITIES } from './cities.mjs';
import { collectAllAlerts } from './alerts.mjs';
import { evaluateEmergency } from './emergency.mjs';
import { geomCentroid, isMain } from './geo.mjs';

export { geomCentroid };

const ALERT_SYSTEMS = Object.freeze(['nws', 'usgs', 'gdacs', 'eonet', 'nhc']);
const OUT = process.argv[2] || 'dispatch-out';
const log = (...a) => console.log(...a);

async function collectCity(city, sources) {
  try {
    const rows = await fetchJson(city.url, { timeoutMs: 30000, retries: 1 });
    if (!Array.isArray(rows)) throw new Error('expected JSON array');
    const { calls, blather } = city.map(rows);
    sources[city.id] = { ok: true, n: calls.length, label: city.label };
    log(`${city.id} ${calls.length} calls`);
    return { calls, blather };
  } catch (e) {
    sources[city.id] = { ok: false, error: String(e.message).slice(0, 160), label: city.label };
    log(`${city.id} FAILED ${sources[city.id].error}`);
    return { calls: [], blather: [] };
  }
}

export const CALLS_PER_CITY = 130;
/** Newest `per` calls from each city, merged newest first. */
export function balancePerCity(calls, per) {
  const by = new Map();
  for (const c of calls.slice().sort((a, b) => b.t - a.t)) {
    const k = c.city || '?', arr = by.get(k) || [];
    if (arr.length < per) arr.push(c);
    by.set(k, arr);
  }
  return [...by.values()].flat().sort((a, b) => b.t - a.t);
}

export async function main() {
  const t0 = Date.now();
  const sources = {};

  const alerts = await collectAllAlerts(sources, log);

  const cityParts = await Promise.all(CITIES.map((c) => collectCity(c, sources)));
  const calls = cityParts.flatMap((p) => p.calls);
  const blather = cityParts.flatMap((p) => p.blather);

  // Deduplicate blather by city+text+minute so the ticker is not a wall of
  // identical Aid Response Yellow lines.
  const seen = new Set();
  const blatherDedup = [];
  const perCityBlather = new Map();
  for (const b of blather.sort((a, b) => b.t - a.t)) {
    const key = `${b.city}|${b.text}|${Math.floor(b.t / 60000)}`;
    if (seen.has(key)) continue;
    seen.add(key);
    // Share the ticker: no single city (often the freshest feed) fills it.
    const n = perCityBlather.get(b.city) || 0;
    if (n >= 60) continue;
    perCityBlather.set(b.city, n + 1);
    blatherDedup.push(b);
    if (blatherDedup.length >= 400) break;
  }

  // Keep every city on the map: newest CALLS_PER_CITY per city, then by time.
  calls.splice(0, calls.length, ...balancePerCity(calls, CALLS_PER_CITY));
  const emergency = evaluateEmergency({ alerts });

  const snap = {
    schema: 2,
    generated: new Date().toISOString(),
    took_ms: Date.now() - t0,
    sources,
    counts: {
      alerts: alerts.length,
      calls: calls.length,
      blather: blatherDedup.length,
      cities_ok: CITIES.filter((c) => sources[c.id]?.ok).length,
      cities: CITIES.length,
      alert_systems_ok: ALERT_SYSTEMS.filter((id) => sources[id]?.ok).length,
      emergency: emergency.active,
    },
    emergency,
    alerts,
    calls: calls.slice(0, 1200),
    blather: blatherDedup,
    cities: CITIES.map((c) => ({
      id: c.id, label: c.label, city: c.city, agency: c.agency,
      ok: !!sources[c.id]?.ok, n: sources[c.id]?.n || 0,
    })),
  };

  if (!alerts.length && !calls.length) {
    throw new Error('every dispatch source failed; refusing to publish an empty snapshot');
  }

  await mkdir(OUT, { recursive: true });
  await writeFile(path.join(OUT, 'dispatch.json'), JSON.stringify(snap));
  // Lightweight file for the site-wide banner (sitebar polls this).
  await writeFile(path.join(OUT, 'emergency.json'), JSON.stringify({
    schema: 1,
    generated: snap.generated,
    ...emergency,
  }));
  await writeFile(
    path.join(OUT, 'README.md'),
    `# dispatch-data\n\nGenerated by dispatch/collect.mjs on main. Force-pushed on every run; do not edit.\n`
    + `Last run: ${snap.generated}\nEmergency: ${emergency.label} (${emergency.count} triggers)\n`,
  );
  log(`wrote ${alerts.length} alerts, ${calls.length} calls, ${blatherDedup.length} blather, emergency=${emergency.label} in ${((Date.now() - t0) / 1000).toFixed(1)} s`);
  return snap;
}

if (isMain(import.meta.url)) main().catch((e) => { console.error(e); process.exit(1); });
