'use strict';
// Generated by tools/keygen.js — the public half of the SIREN license signing key.
module.exports = { PUBLIC_KEY_SPKI_B64: 'MCowBQYDK2VwAyEAY8vjmYXBMRv37OI7KpPl1g85M7ak0pmvIUFuSmhPVd8=' };
